name: dices_supporter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+4   #app bundle개시시 +X부분을 수정하여 버전을 갱신할것

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.5
  easy_localization: ^3.0.0
  fluttertoast: ^4.0.1
  flutter:
    sdk: flutter
  page_transition : ^1.1.7+6

  cupertino_icons: ^1.0.2

  lite_rolling_switch: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4

flutter:
  uses-material-design: true
  assets:
    - assets/en-US.json
    - assets/ko-KR.json
    - assets/ja-JP.json
    - images/dice1.png
    - images/dice2.png
    - images/dice3.png
    - images/dice4.png
    - images/dice5.png
    - images/dice6.png
    - images/easterEgg/easterEgg.png
    - android/app/src/main/res/values/

flutter_native_splash:
  background_image: "images/splash/splash.png"
  fullscreen: true


  #flutter pub pub run flutter_native_splash:create <-스플래시 적용시엔 터미널에 입력할 것
