name: dices_supporter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+5   #app bundle개시시 +X부분을 수정하여 버전을 갱신할것

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.5
  easy_localization: ^3.0.3
  fluttertoast: ^8.2.4
  flutter:
    sdk: flutter
  page_transition : ^2.1.0

  cupertino_icons: ^1.0.2

  lite_rolling_switch: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/en-US.json
    - assets/ko-KR.json
    - assets/ja-JP.json
    - images/kanji/
    - images/normal/
    - images/number/
    - images/rome/
    - images/easterEgg/easterEgg.png
    - android/app/src/main/res/values/

flutter_native_splash:
  background_image: "images/splash/splash.png"
  fullscreen: true


  #flutter pub pub run flutter_native_splash:create <-스플래시 적용시엔 터미널에 입력할 것

dependency_overrides:
  intl: ^0.19.0